# Generated by Django 3.2 on 2022-05-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
