# Generated by Django 3.2 on 2022-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_rename_contact_id_group_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contact',
        ),
        migrations.AddField(
            model_name='group',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='testApp.Contact'),
        ),
    ]
