# Generated by Django 3.2 on 2022-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20220512_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='contact',
            new_name='contacts',
        ),
    ]
